# -*- coding: utf-8 -*-
"""BDP_process_analysis_index.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FFAMag7N7b91I1nDECFVwk705mlFNfF3
"""

!pip install pyspark

# 📌 Colab 파일 업로드
from google.colab import files

uploaded = files.upload()

# 업로드한 파일명을 자동으로 가져오기
file_name = list(uploaded.keys())[0]
print("업로드된 파일:", file_name)

# 파일을 '/content/gold_features.csv' 로 이동/저장
import shutil
shutil.move(file_name, "/content/gold_features.csv")

print("파일 저장 완료 → /content/gold_features.csv")

# 🔧 utils.py 역할 — 엔트로피 UDF 정의

from pyspark.sql.types import FloatType
from pyspark.sql import functions as F
import math

def entropy_py(values):
    if values is None or len(values) == 0:
        return None
    total = len(values)
    counts = {}
    for v in values:
        counts[v] = counts.get(v, 0) + 1
    ent = 0
    for c in counts.values():
        p = c / total
        ent += -p * math.log(p)
    return float(ent)

entropy_udf = F.udf(entropy_py, FloatType())

# ============================
# PROCESSED MONTHLY (Daily 스킵 버전)
# ============================

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import FloatType
import math
from google.colab import files  # ⬅ 자동 다운로드용

def entropy_py(values):
    if values is None or len(values) == 0:
        return None
    total = len(values)
    counts = {}
    for v in values:
        counts[v] = counts.get(v, 0) + 1
    ent = 0
    for c in counts.values():
        p = c / total
        ent += -p * math.log(p)
    return float(ent)

entropy_udf = F.udf(entropy_py, FloatType())

spark = SparkSession.builder.appName("ProcessedMonthlyTest").getOrCreate()

# -------------------------
# Gold 로드 (이미 월 단위)
# -------------------------
gold = (
    spark.read
        .option("header", True)
        .option("multiLine", True)
        .option("escape", "\"")
        .csv("/content/gold_features.csv")
)

# 필요한 컬럼 캐스팅
gold = (
    gold.withColumn("engagement_score", F.col("engagement_score").cast("float"))
        .withColumn("topic_id", F.col("topic_id").cast("int"))
        .withColumn("keyword_entropy", F.col("keyword_entropy").cast("float"))
        .withColumn("sentiment_score", F.col("sentiment_score").cast("float"))
        .withColumn("cross_blog_similarity", F.col("cross_blog_similarity").cast("float"))
        .withColumn("semantic_novelty", F.col("semantic_novelty").cast("float"))
        .withColumn("gold_processed_at", F.to_timestamp("gold_processed_at"))
)

# -------------------------
# 월 시작일 생성
# -------------------------
gold = gold.withColumn("month_start", F.trunc("gold_processed_at", "month"))

# -------------------------
# 월 단위 집계
# -------------------------
monthly = (
    gold.groupBy("emd_cd", "month_start")
    .agg(
        F.countDistinct("post_id").alias("post_density"),
        F.sum("engagement_score").alias("total_engagement"),
        F.avg("engagement_score").alias("avg_engagement"),

        F.avg("sentiment_score").alias("avg_sentiment"),
        F.avg((F.col("sentiment_label") == "positive").cast("double")).alias("pos_ratio"),
        F.stddev_pop("sentiment_score").alias("sentiment_volatility"),

        entropy_udf(F.collect_list("topic_id")).alias("topic_diversity"),
        F.avg("keyword_entropy").alias("keyword_entropy_avg"),
        F.avg("semantic_novelty").alias("semantic_novelty_avg"),
        F.avg("cross_blog_similarity").alias("cross_blog_similarity_avg")
    )
    .withColumn("processed_at", F.current_timestamp())
)

monthly.write.mode("overwrite").parquet("/content/processed_blog_monthly_test")

print("🎉 Processed Monthly (Daily 생략 테스트 버전) 생성 완료!")
monthly.show(10)

# -----------------------------
# 7) CSV로 저장 (단일 파일)
# -----------------------------
csv_dir = "/content/processed_blog_monthly_test_csv"

(
    monthly
    .coalesce(1)
    .write
    .option("header", True)
    .mode("overwrite")
    .csv(csv_dir)
)

print("📁 CSV 파일 생성 완료! →", csv_dir)

# -----------------------------
# 8) 자동 다운로드
# -----------------------------
import glob
csv_path = glob.glob(csv_dir + "/*.csv")[0]   # 생성된 파일 선택

print("📥 자동 다운로드 중:", csv_path)
files.download(csv_path)

#Analysis
# =============================================
# ANALYSIS MONTHLY (Processed Monthly → Analysis)
# =============================================

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.window import Window
from google.colab import files  # ⬅ 자동 다운로드용

spark = SparkSession.builder.appName("AnalysisMonthlyTest").getOrCreate()

# ---------------------------------------------
# 1. Load Processed Monthly
# ---------------------------------------------
monthly = spark.read.parquet("/content/processed_blog_monthly_test")

# ---------------------------------------------
# 2. Window 생성
# ---------------------------------------------
w = Window.partitionBy("emd_cd").orderBy("month_start")

# ---------------------------------------------
# 3. Momentum
# ---------------------------------------------
monthly = monthly.withColumn("prev_pd", F.lag("post_density").over(w))
monthly = monthly.withColumn(
    "momentum",
    (F.col("post_density") - F.col("prev_pd")) /
    (F.col("prev_pd") + F.lit(1e-6))
)

# ---------------------------------------------
# 4. Trend Strength
# ---------------------------------------------
monthly = monthly.withColumn("t", F.row_number().over(w))
monthly = monthly.withColumn("t_pd", F.col("t") * F.col("post_density"))
monthly = monthly.withColumn(
    "cov_t_pd",
    F.avg("t_pd").over(w) -
    (F.avg("t").over(w) * F.avg("post_density").over(w))
)
monthly = monthly.withColumn("var_t", F.var_pop("t").over(w))
monthly = monthly.withColumn(
    "trend_strength",
    F.col("cov_t_pd") / (F.col("var_t") + F.lit(1e-6))
)

# ---------------------------------------------
# 5. Analysis Schema
# ---------------------------------------------
analysis = (
    monthly.select(
        F.lit("monthly").alias("period_type"),
        F.col("month_start").alias("period_start"),
        F.last_day("month_start").alias("period_end"),
        "emd_cd",
        "post_density",
        "avg_engagement",
        "avg_sentiment",
        "pos_ratio",
        "sentiment_volatility",
        "topic_diversity",
        "keyword_entropy_avg",
        "semantic_novelty_avg",
        "momentum",
        "trend_strength"
    )
    .withColumn("processed_at", F.current_timestamp())
)

# ---------------------------------------------
# 6. Save as CSV (single file)
# ---------------------------------------------
output_dir = "/content/analysis_blog_monthly_test_csv"

(
    analysis
    .coalesce(1)
    .write
    .option("header", True)
    .mode("overwrite")
    .csv(output_dir)
)

print("📁 Analysis Monthly CSV 생성 완료!")

# ---------------------------------------------
# 7. Find actual CSV file and auto-download
# ---------------------------------------------
import glob

csv_path = glob.glob(output_dir + "/*.csv")[0]  # 첫 번째 CSV 파일 찾기
print("📥 다운로드 파일:", csv_path)

files.download(csv_path)  # ⬅ 자동 다운로드 실행

# Show result
analysis.show(20)

# Index
# =============================================
# INDEX MONTHLY (Analysis → Final Index)
# =============================================

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.window import Window

spark = SparkSession.builder.appName("IndexMonthlyTest").getOrCreate()

# ---------------------------------------------
# 1. Load Analysis Monthly
# ---------------------------------------------
analysis = spark.read.parquet("/content/analysis_blog_monthly_test")

# ---------------------------------------------
# 2. z-score normalization helper
# ---------------------------------------------
def z(col):
    return (F.col(col) - F.mean(col).over(Window.partitionBy())) / \
           (F.stddev_pop(col).over(Window.partitionBy()) + F.lit(1e-6))

# ---------------------------------------------
# 3. Score Components
# ---------------------------------------------
index = analysis \
    .withColumn("activity_score", z("post_density") + z("avg_engagement")) \
    .withColumn("sentiment_score", z("avg_sentiment") + z("pos_ratio") - z("sentiment_volatility")) \
    .withColumn("semantic_score", z("topic_diversity") + z("keyword_entropy_avg") + z("semantic_novelty_avg")) \
    .withColumn("trend_score", z("momentum") + z("trend_strength"))

# ---------------------------------------------
# 4. Final Index
# ---------------------------------------------
index = index.withColumn(
    "unstructured_index",
    0.25 * F.col("activity_score") +
    0.25 * F.col("sentiment_score") +
    0.30 * F.col("semantic_score") +
    0.20 * F.col("trend_score")
)

# ---------------------------------------------
# 5. Ranking & metadata
# ---------------------------------------------
w = Window.partitionBy("period_start").orderBy(F.col("unstructured_index").desc())

index = index \
    .withColumn("index_rank", F.row_number().over(w)) \
    .withColumn("index_version", F.lit("v1.0")) \
    .withColumn("calculated_at", F.current_timestamp())

# ---------------------------------------------
# 6. Save
# ---------------------------------------------
index.write.mode("overwrite").parquet("/content/blog_unstructured_index_test")

print("🎉 Index Monthly 생성 완료!")
index.show(20)

