# -*- coding: utf-8 -*-
"""gold_layer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gkwQ_J2L5_1OeqxUwW4IoWmn4C6gMeFv
"""

!sudo apt-get update -y
!sudo apt-get install python3.10 python3.10-distutils python3.10-dev -y
!curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10

import sys
sys.executable = "/usr/bin/python3.10"

!python3.10 -m pip install --upgrade pip
!python3.10 -m pip install pandas numpy
!python3.10 -m pip install numba==0.57.1 llvmlite==0.40.1
!python3.10 -m pip install umap-learn hdbscan
!python3.10 -m pip install sentence-transformers bertopic[all]
!python3.10 -m pip install keybert
!python3.10 -m pip install transformers
!python3.10 -m pip install torch --index-url https://download.pytorch.org/whl/cu121

import sys
print(sys.version)

import torch
import pandas as pd
import numpy as np
import json
from datetime import datetime

from umap import UMAP
from hdbscan import HDBSCAN

from sentence_transformers import SentenceTransformer
from bertopic import BERTopic
from keybert import KeyBERT

from transformers import AutoTokenizer, AutoModelForSequenceClassification

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def to_json_list(x):
    if x is None:
        return None
    cleaned = []
    for v in x:
        if isinstance(v, (int, float, np.float32, np.float64)):
            cleaned.append(float(v))
        else:
            cleaned.append(str(v))
    return json.dumps(cleaned, ensure_ascii=False)

def keyword_entropy(weights):
    if len(weights) == 0:
        return 0.0
    w = np.array(weights, dtype=float)
    if w.sum() == 0:
        return 0.0
    p = w / w.sum()
    p = p[p > 0]
    return float(-(p * np.log(p)).sum())

def calc_cross_similarity(embeddings):
    n = embeddings.shape[0]
    sims = np.zeros(n, dtype=float)
    if n <= 1:
        return sims
    for i in range(1, n):
        prev = embeddings[:i]
        cur = embeddings[i:i+1]
        cs = cosine_similarity(cur, prev)[0]
        sims[i] = cs.mean()
    return sims

device = "cuda" if torch.cuda.is_available() else "cpu"
device

from google.colab import files
uploaded = files.upload()   # 버튼 눌러서 silver_output.csv 업로드

INPUT_CSV = list(uploaded.keys())[0]
OUTPUT_CSV = "gold_output.csv"

df = pd.read_csv(INPUT_CSV)
df.columns

df = pd.read_csv(INPUT_CSV)

# ---- Silver metadata 보관 ----
silver_cols = df[[
    "post_id",
    "link",
    "administrative_dong",
    "title",
    "hashtags",
    "like_count",
    "comment_count",
    "engagement_score"
]].copy()

# ---- Gold NLP df에서는 Silver 컬럼 제거 ----
df = df.drop(columns=[
    "post_id",
    "link",
    "administrative_dong",
    "title",
    "hashtags",
    "like_count",
    "comment_count",
    "engagement_score"
])

# ---- required cols 수정 (post_id 제거!) ----
required_cols = ["text_clean"]
for c in required_cols:
    if c not in df.columns:
        raise ValueError(f"Missing column: {c}")

df["text_clean"] = df["text_clean"].astype(str)
df = df.dropna(subset=["text_clean"]).copy()

docs = df["text_clean"].tolist()
n_docs = len(docs)

print("[INFO] Number of docs:", n_docs)

print("[INFO] Loading KoSimCSE model...")
embed_model = SentenceTransformer("BM-K/KoSimCSE-roberta-multitask")

print("[INFO] Encoding documents...")
embeddings = embed_model.encode(docs, batch_size=32, show_progress_bar=True)
embeddings = np.array(embeddings)

df["embedding_vector"] = [to_json_list(e) for e in embeddings]

"""1) KoSimCSE (SentenceTransformer) — 문장 임베딩 모델
2) BERTopic — 주제(Topic) 모델링
3) KeyBERT — 문서 내 핵심 키워드 추출
4) TF-IDF — 빈도 기반 키워드(통계적 특징) 추출
5) KcELECTRA — 한국어 감정 분석 모델 (Sentiment)
6) Similarity & Novelty — 신선도/중복도 측정 모델
7) Geocoding Stub (임시 기능)

| 모델                | 역할        | 설명                  |
| ----------------- | --------- | ------------------- |
| KoSimCSE          | 임베딩       | 문장을 의미 벡터로 변환       |
| UMAP              | 차원축소      | 고차원 → 저차원 구조 유지     |
| HDBSCAN           | 클러스터링     | 토픽 자동 생성            |
| BERTopic          | 토픽 모델링    | 토픽 ID, 키워드 생성       |
| KeyBERT           | 의미 기반 키워드 | 문서 핵심 단어 top-5      |
| TF-IDF            | 통계 기반 키워드 | 단어 빈도 기반 top-10     |
| KcELECTRA         | 감정 분석     | 긍정/부정/중립            |
| cosine similarity | 중복도/새로움   | semantic novelty 계산 |

"""

print("[INFO] BERTopic 시작")

# --------------------------------------------------------
# 0. 데이터 크기 출력
# --------------------------------------------------------
print(f"[INFO] 문서 개수: {len(docs)}")


# --------------------------------------------------------
# 1. UMAP + HDBSCAN 모델 세팅 단계 (진행 로그)
# --------------------------------------------------------
if len(docs) < 50:
    print("[BERTopic] 작은 문서 집합 → 커스텀 UMAP/HDBSCAN 사용")

    print("[BERTopic] UMAP 설정 중...")
    umap_model = UMAP(
        n_neighbors=max(2, min(5, len(docs)-1)),
        n_components=2,
        min_dist=0.0,
        metric="cosine"
    )
    print("[BERTopic] UMAP 설정 완료")

    print("[BERTopic] HDBSCAN 설정 중...")
    hdbscan_model = HDBSCAN(
        min_cluster_size=2,
        min_samples=1,
        metric="euclidean",
        prediction_data=True
    )
    print("[BERTopic] HDBSCAN 설정 완료")

    print("[BERTopic] BERTopic 모델 생성 중...")
    topic_model = BERTopic(
        embedding_model=embed_model,
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        verbose=True   # 내부 진행 로그 활성화
    )
else:
    print("[BERTopic] 기본 BERTopic 모델 생성 중...")
    topic_model = BERTopic(embedding_model=embed_model, verbose=True)


# --------------------------------------------------------
# 2. 토픽 학습 단계 (fit_transform)
# --------------------------------------------------------
print("[BERTopic] fit_transform 시작 (토픽 모델 학습 중)...")
topics, probs = topic_model.fit_transform(docs)
print("[BERTopic] fit_transform 완료")


# --------------------------------------------------------
# 3. 결과 DataFrame 저장 단계
# --------------------------------------------------------
df["topic_id"] = topics
df["topic_probability"] = probs
print("[BERTopic] 토픽 ID 및 확률 저장 완료")


# --------------------------------------------------------
# 4. 각 토픽별 키워드 추출 단계
# --------------------------------------------------------
print("[BERTopic] 토픽 키워드 추출 시작...")

topic_keywords_map = {}

unique_topics = set(topics)
print(f"[BERTopic] 총 토픽 개수: {len(unique_topics)}")

for i, tid in enumerate(unique_topics):
    if tid == -1:
        topic_keywords_map[tid] = []
        print(f"[BERTopic] [{i+1}/{len(unique_topics)}] -1(노이즈) 토픽 처리 완료")
        continue

    words = topic_model.get_topic(tid)
    topic_keywords_map[tid] = [w for (w, _) in words]
    print(f"[BERTopic] [{i+1}/{len(unique_topics)}] 토픽 {tid} 키워드 추출 완료")

df["topic_keywords"] = df["topic_id"].map(
    lambda tid: to_json_list(topic_keywords_map.get(tid, []))
)

print("[BERTopic] 토픽 키워드 매핑 완료")
print("[INFO] BERTopic 전체 처리 완료")

# ================================================
# KEYBERT
# ================================================
print("[INFO] Running KeyBERT...")

kb_model = KeyBERT(model=embed_model)
doc_keywords_list = []

print(f"[KeyBERT] 총 문서: {n_docs}")
for i, t in enumerate(docs):
    if i % 50 == 0 or i == n_docs - 1:
        print(f"[KeyBERT] 처리 중... {i+1}/{n_docs}")

    kws = kb_model.extract_keywords(t, top_n=5)
    doc_keywords_list.append([w for (w, _) in kws])

df["doc_keywords"] = [to_json_list(k) for k in doc_keywords_list]
print("[KeyBERT] 완료")


# ================================================
# TF-IDF
# ================================================
print("[INFO] Running TF-IDF...")

print("[TF-IDF] 벡터라이저 학습 중...")
tfidf_vectorizer = TfidfVectorizer(max_features=10000, ngram_range=(1,2), min_df=2)
tfidf_matrix = tfidf_vectorizer.fit_transform(docs)
feature_names = np.array(tfidf_vectorizer.get_feature_names_out())

print("[TF-IDF] 키워드 추출 중...")
tfidf_keywords = []
entropy_list = []
top_k_tfidf = 10

for i in range(n_docs):
    if i % 50 == 0 or i == n_docs - 1:
        print(f"[TF-IDF] 처리 중... {i+1}/{n_docs}")

    row = tfidf_matrix.getrow(i)

    if row.nnz == 0:
        tfidf_keywords.append([])
        entropy_list.append(0.0)
        continue

    data = row.data
    idx = np.argsort(data)[-top_k_tfidf:]
    terms = feature_names[row.indices[idx]]
    weights = data[idx]

    tfidf_keywords.append(list(terms))
    entropy_list.append(keyword_entropy(weights))

df["keyword_list_tfidf"] = [to_json_list(k) for k in tfidf_keywords]
df["keyword_entropy"] = entropy_list
print("[TF-IDF] 완료")


# ================================================
# SENTIMENT (KcELECTRA)
# ================================================
print("[INFO] Running Sentiment...")

sent_model_name = "beomi/KcELECTRA-base-v2022"
sent_tokenizer = AutoTokenizer.from_pretrained(sent_model_name)
sent_model = AutoModelForSequenceClassification.from_pretrained(sent_model_name).to(device)

scores = []
labels = []

print(f"[Sentiment] 총 문서: {n_docs} / batch=16")
for i in range(0, n_docs, 16):
    if i % 160 == 0 or i + 16 >= n_docs:
        print(f"[Sentiment] 처리 중... {i+1}/{n_docs}")

    batch_texts = docs[i:i+16]
    inputs = sent_tokenizer(
        batch_texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=128
    ).to(device)

    with torch.no_grad():
        logits = sent_model(**inputs).logits
        prob = torch.softmax(logits, dim=-1)

    pos_prob = prob[:,1].cpu().numpy()
    score = 2 * pos_prob - 1

    scores.extend(score.tolist())

    for s in score:
        if s > 0.2:
            labels.append("positive")
        elif s < -0.2:
            labels.append("negative")
        else:
            labels.append("neutral")

df["sentiment_score"] = scores
df["sentiment_label"] = labels
print("[Sentiment] 완료")


# ================================================
# Similarity & Novelty
# ================================================
print("[INFO] Computing similarity...")

print("[Similarity] 계산 중...")
cross_sim = calc_cross_similarity(embeddings)
df["cross_blog_similarity"] = cross_sim
df["semantic_novelty"] = 1.0 - cross_sim

print("[Similarity] 완료")


# ================================================
# Geocode Stub
# ================================================
print("[INFO] Geocode Stub 처리...")

df["emd_cd"] = df.get("emd_cd", None)

# ================================================
# 처리 로그
# ================================================
df["gold_processed_at"] = datetime.utcnow().isoformat()

print("[INFO] 처리 로그 생성 완료")


# ================================================
# GOLD 컬럼만 남기기
# ================================================
print("[INFO] Gold 컬럼 필터링 중...")

# ---- Silver + Gold 결합 ----
df = pd.concat([silver_cols, df], axis=1)

keep_cols = [
    # Silver metadata
    "post_id",
    "link",
    "administrative_dong",
    "title",
    "hashtags",
    "like_count",
    "comment_count",
    "engagement_score",

    # Gold outputs
    "embedding_vector",
    "topic_id",
    "topic_keywords",
    "topic_probability",
    "doc_keywords",
    "keyword_list_tfidf",
    "keyword_entropy",
    "sentiment_score",
    "sentiment_label",
    "cross_blog_similarity",
    "semantic_novelty",
    "emd_cd",
    "gold_processed_at"
]

# 없는 컬럼 자동 생성
for col in keep_cols:
    if col not in df.columns:
        print(f"[WARN] {col} 컬럼 없음 → 자동 생성")
        df[col] = None

df = df[keep_cols]

print("[INFO] GOLD 컬럼 정리 완료 (Silver + NLP 통합 스키마 적용)")

print(df.columns.tolist())

df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
print("Saved:", OUTPUT_CSV)

from google.colab import files
files.download(OUTPUT_CSV)