# -*- coding: utf-8 -*-
"""silver_layer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14hfhEG1Js5jvVlUtgE0UtNYSA2dCSuZD
"""

# Java 설치
!apt-get install openjdk-11-jdk-headless -qq > /dev/null

# Spark 3.5.0 다운로드
!wget -q https://archive.apache.org/dist/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz

# 압축 해제
!tar xf spark-3.5.0-bin-hadoop3.tgz

# PySpark 설치
!pip install -q pyspark findspark

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.5.0-bin-hadoop3"

import findspark
findspark.init()

from pyspark.sql import SparkSession
spark = SparkSession.builder \
    .appName("SilverLayerTest") \
    .getOrCreate()

spark

from google.colab import files
uploaded = files.upload()   # 여기서 CSV를 업로드한다

df = spark.read.csv("blog_posts_성수동_명소_202212.csv",
                    header=True,
                    multiLine=True,
                    escape='"')
df.printSchema()
df.show(3, truncate=False)

from pyspark.sql import SparkSession
from pyspark.sql.functions import *
import pyspark.sql.functions as F

spark = SparkSession.builder.appName("SilverLayerSimple").getOrCreate()

# 1) Raw CSV 로드
df = spark.read.csv(
    "/content/blog_posts_성수동_명소_202212.csv",
    header=True,
    multiLine=True,
    escape='"'
)

# ==========================
# Silver 변환 시작
# ==========================

# HTML 제거
def strip_html(col):
    return regexp_replace(col, "<[^>]+>", " ")

# 이모지 제거 (기본 문자만 허용)
emoji_regex = "[^\uAC00-\uD7A3a-zA-Z0-9 .,!?]"

# 최소 UI 노이즈만 제거
noise_regex = (
    "(재생\\s+[0-9]+)"
    "|(좋아요\\s+[0-9]+)"
    "|URL 복사"
    "|본문 기타 기능"
)

# 저작권은 한 줄만 제거
copyright_regex = "©[^\\n]+"

# --------------------------
# title 정제
# --------------------------
df = df.withColumn(
    "title",
    trim(
        regexp_replace(
            strip_html(col("title")),
            emoji_regex,
            " "
        )
    )
)

# --------------------------
# content 정제
# --------------------------
clean = strip_html(col("content_raw"))

clean = regexp_replace(clean, noise_regex, " ")
clean = regexp_replace(clean, copyright_regex, " ")
clean = regexp_replace(clean, "http\\S+", " ")
clean = regexp_replace(clean, emoji_regex, " ")
clean = regexp_replace(clean, "\\s+", " ")

df = df.withColumn("text_clean", trim(clean))

# --------------------------
# 단어 수
# --------------------------
df = df.withColumn("content_length", size(split(col("text_clean"), " ")))

# --------------------------
# hashtags 문자열 → 배열 변환
# --------------------------
df = df.withColumn(
    "hashtags",
    split(
        regexp_replace(regexp_replace(col("hashtags"), "[\\[\\]']", ""), "\\s*,\\s*", ","),
        ","
    )
)

# --------------------------
# like/comment 캐스팅
# --------------------------
df = df.withColumn("like_count", col("like_count").cast("int"))
df = df.withColumn("comment_count", col("comment_count").cast("int"))

# --------------------------
# engagement score
# --------------------------
df = df.withColumn(
    "engagement_score",
    log1p(col("like_count") + col("comment_count"))
)

# ==========================
# Silver Schema 선택
# ==========================
silver_df = df.select(
    "post_id",
    "link",
    "administrative_dong",
    "title",
    "text_clean",
    "content_length",
    "hashtags",
    "like_count",
    "comment_count",
    "engagement_score"
)

silver_df.show(5, truncate=False)

# Spark DF → Pandas DF 변환
pdf = silver_df.toPandas()

# CSV 저장
csv_path = "silver_output.csv"
pdf.to_csv(csv_path, index=False, encoding="utf-8-sig")

# Colab 다운로드
from google.colab import files
files.download(csv_path)

silver_df.write.mode("overwrite").parquet("blog_silver.parquet")

"""여기 밑으로 파이썬 변환"""

!pip install pandas numpy

from google.colab import files
uploaded = files.upload()

INPUT_CSV = list(uploaded.keys())[0]
print("Loaded:", INPUT_CSV)

import pandas as pd
import numpy as np
import re

# CSV 로드
df = pd.read_csv(INPUT_CSV)

# ----------------------------
# HTML 제거 함수
# ----------------------------
def strip_html(text):
    if pd.isna(text):
        return ""
    return re.sub(r"<[^>]+>", " ", text)

# Emoji 제거 (Spark regex 동일)
emoji_pattern = re.compile(r"[^\uAC00-\uD7A3a-zA-Z0-9 .,!?]")

# 최소 UI 노이즈 제거
noise_regex = re.compile(
    r"(재생\s+[0-9]+)"
    r"|(좋아요\s+[0-9]+)"
    r"|URL 복사"
    r"|본문 기타 기능"
)

# 저작권 한 줄 제거
copyright_regex = re.compile(r"©[^\n]+")

# ----------------------------
# title 정제
# ----------------------------
def clean_title(text):
    if pd.isna(text):
        return ""
    text = strip_html(text)
    text = emoji_pattern.sub(" ", text)
    return " ".join(text.split())

df["title"] = df["title"].apply(clean_title)

# ----------------------------
# content_raw 정제 → text_clean 생성
# ----------------------------
def clean_content(text):
    if pd.isna(text):
        return ""

    text = strip_html(text)
    text = noise_regex.sub(" ", text)
    text = copyright_regex.sub(" ", text)
    text = re.sub(r"http\S+", " ", text)
    text = emoji_pattern.sub(" ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df["text_clean"] = df["content_raw"].apply(clean_content)

# ----------------------------
# content_length (단어 수)
# ----------------------------
df["content_length"] = df["text_clean"].apply(lambda x: len(x.split()))

# ----------------------------
# hashtags → 배열 변환 (Spark 로직 동일)
# ----------------------------
def parse_hashtags(text):
    if pd.isna(text):
        return []
    text = text.replace("[", "").replace("]", "").replace("'", "")
    parts = [x.strip() for x in text.split(",") if x.strip()]
    return parts

df["hashtags"] = df["hashtags"].apply(parse_hashtags)

# ----------------------------
# like/comment 타입 캐스팅
# ----------------------------
df["like_count"] = pd.to_numeric(df["like_count"], errors="coerce").fillna(0).astype(int)
df["comment_count"] = pd.to_numeric(df["comment_count"], errors="coerce").fillna(0).astype(int)

# ----------------------------
# engagement_score = log1p(like + comment)
# ----------------------------
df["engagement_score"] = np.log1p(df["like_count"] + df["comment_count"])

# ----------------------------
# 최종 Silver Schema 선택
# ----------------------------
silver_df = df[[
    "post_id",
    "link",
    "administrative_dong",
    "title",
    "text_clean",
    "content_length",
    "hashtags",
    "like_count",
    "comment_count",
    "engagement_score"
]]

silver_df.head()

csv_path = "silver_output.csv"
silver_df.to_csv(csv_path, index=False, encoding="utf-8-sig")

from google.colab import files
files.download(csv_path)